


CREATE INDEX IF NOT EXISTS "users_platform_role_idx" ON "users"("platform_role");
CREATE INDEX IF NOT EXISTS "users_is_active_idx" ON "users"("is_active");
CREATE INDEX IF NOT EXISTS "cities_name_idx" ON "cities"("name");
CREATE INDEX IF NOT EXISTS "restaurants_is_active_idx" ON "restaurants"("is_active");
CREATE INDEX IF NOT EXISTS "restaurants_city_id_idx" ON "restaurants"("city_id");
CREATE INDEX IF NOT EXISTS "restaurants_is_active_created_at_idx" ON "restaurants"("is_active", "created_at");
CREATE INDEX IF NOT EXISTS "permissions_module_idx" ON "permissions"("module");
CREATE INDEX IF NOT EXISTS "roles_restaurant_id_idx" ON "roles"("restaurant_id");
CREATE INDEX IF NOT EXISTS "role_permissions_role_id_idx" ON "role_permissions"("role_id");
CREATE INDEX IF NOT EXISTS "role_permissions_permission_id_idx" ON "role_permissions"("permission_id");
CREATE INDEX IF NOT EXISTS "restaurant_staff_user_id_idx" ON "restaurant_staff"("user_id");
CREATE INDEX IF NOT EXISTS "restaurant_staff_restaurant_id_idx" ON "restaurant_staff"("restaurant_id");
CREATE INDEX IF NOT EXISTS "restaurant_staff_role_id_idx" ON "restaurant_staff"("role_id");
CREATE INDEX IF NOT EXISTS "plans_name_idx" ON "plans"("name");
CREATE INDEX IF NOT EXISTS "subscriptions_restaurant_id_idx" ON "subscriptions"("restaurant_id");
CREATE INDEX IF NOT EXISTS "subscriptions_plan_id_idx" ON "subscriptions"("plan_id");
CREATE INDEX IF NOT EXISTS "subscriptions_status_idx" ON "subscriptions"("status");
CREATE INDEX IF NOT EXISTS "subscriptions_restaurant_id_status_idx" ON "subscriptions"("restaurant_id", "status");
CREATE INDEX IF NOT EXISTS "subscriptions_restaurant_id_period_end_idx" ON "subscriptions"("restaurant_id", "period_end");
CREATE INDEX IF NOT EXISTS "branches_restaurant_id_idx" ON "branches"("restaurant_id");
CREATE INDEX IF NOT EXISTS "branches_city_id_idx" ON "branches"("city_id");
CREATE INDEX IF NOT EXISTS "branches_restaurant_id_is_active_idx" ON "branches"("restaurant_id", "is_active");
CREATE INDEX IF NOT EXISTS "menu_images_restaurant_id_idx" ON "menu_images"("restaurant_id");
CREATE INDEX IF NOT EXISTS "menu_images_branch_id_idx" ON "menu_images"("branch_id");
CREATE INDEX IF NOT EXISTS "menu_images_restaurant_id_branch_id_idx" ON "menu_images"("restaurant_id", "branch_id");
CREATE INDEX IF NOT EXISTS "gallery_restaurant_id_idx" ON "gallery"("restaurant_id");
CREATE INDEX IF NOT EXISTS "employees_restaurant_id_idx" ON "employees"("restaurant_id");
CREATE INDEX IF NOT EXISTS "employees_branch_id_idx" ON "employees"("branch_id");
CREATE INDEX IF NOT EXISTS "employees_name_idx" ON "employees"("name");
CREATE INDEX IF NOT EXISTS "qr_codes_restaurant_id_idx" ON "qr_codes"("restaurant_id");
CREATE INDEX IF NOT EXISTS "qr_codes_code_is_active_idx" ON "qr_codes"("code", "is_active");
CREATE INDEX IF NOT EXISTS "qr_codes_restaurant_id_is_active_idx" ON "qr_codes"("restaurant_id", "is_active");
CREATE INDEX IF NOT EXISTS "reviews_restaurant_id_idx" ON "reviews"("restaurant_id");
CREATE INDEX IF NOT EXISTS "reviews_branch_id_idx" ON "reviews"("branch_id");
CREATE INDEX IF NOT EXISTS "reviews_created_at_idx" ON "reviews"("created_at");
CREATE INDEX IF NOT EXISTS "reviews_restaurant_id_created_at_idx" ON "reviews"("restaurant_id", "created_at");
CREATE INDEX IF NOT EXISTS "reviews_restaurant_id_overall_rating_idx" ON "reviews"("restaurant_id", "overall_rating");
CREATE INDEX IF NOT EXISTS "complaints_restaurant_id_idx" ON "complaints"("restaurant_id");
CREATE INDEX IF NOT EXISTS "complaints_branch_id_idx" ON "complaints"("branch_id");
CREATE INDEX IF NOT EXISTS "complaints_status_idx" ON "complaints"("status");
CREATE INDEX IF NOT EXISTS "complaints_category_id_idx" ON "complaints"("category_id");
CREATE INDEX IF NOT EXISTS "complaints_employee_id_idx" ON "complaints"("employee_id");
CREATE INDEX IF NOT EXISTS "complaints_restaurant_id_status_idx" ON "complaints"("restaurant_id", "status");
CREATE INDEX IF NOT EXISTS "complaints_restaurant_id_created_at_idx" ON "complaints"("restaurant_id", "created_at");
CREATE INDEX IF NOT EXISTS "audit_logs_user_id_idx" ON "audit_logs"("user_id");
CREATE INDEX IF NOT EXISTS "audit_logs_restaurant_id_idx" ON "audit_logs"("restaurant_id");
CREATE INDEX IF NOT EXISTS "audit_logs_action_idx" ON "audit_logs"("action");
CREATE INDEX IF NOT EXISTS "audit_logs_entity_idx" ON "audit_logs"("entity");
CREATE INDEX IF NOT EXISTS "audit_logs_restaurant_id_action_idx" ON "audit_logs"("restaurant_id", "action");
